site_name: Fizyo Paylaş
site_url: https://adamagar.github.io/fizyo-paylas
theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/f
  favicon: assets/fizyo_paylas.ico
  features:
    - navigation.footer
    - navigation.indexes
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "© 2025 FizyoPaylaş. Tüm hakları saklıdır."

nav:
  - Ana Sayfa: index.md
  - Katıl: katil.md
  - Moderatörler: moderatorler.md
  - Geçmiş Moderatörler: gecmisModeratorler.md
  - Destekçiler: destekciler.md
  - Blog:
      - Hastanın Hedefini Anlamak: blog/2025-07-15-hasta-hedef.md

extra:
  blog_posts:
    - title: "Hastanın Beklentilerini ve Hedeflerini Anlamak"
      url: blog/2025-07-15-hasta-hedef/
      date: 2025-07-15
      author: "Adam Agar"
      author_avatar: assets/avatar/adam.jpg
      read_time: 2
      description: "Hastanın ilk seansta terapiden ne beklediğini ve kişisel hedeflerini nasıl anlamalıyız?"

plugins:
  - blog
  - macros
